### ISSUE TITLE
It would be really great if this worked on AR headsets too

### ISSUE THREAD

**Issue by AdaRoseCannon** [MozillaReality/jumpy-balls#30]
The gameplay seems like it would work really well on AR headsets and it would be neat if there was a button for entering immersive AR.

As a plus if it also supported hand interaction that would be cool too.

**Comment by DevPika** [comment]
Now with passthrough being accessible inside the Quest 2 browser, I wanted to pick this up too! Sadly I didn't get too far with this, as setting up a consistent dev environment seemed difficult. I tried using `npm ci` to use the exact versions of the modules but still no luck. I gave up towards the end as it looked like three-ecsy and this project both seemed to be abandoned...

**Comment by DevPika** [comment]
I didn't give up, and it was worth sticking it out! I was able to trace back the problem a few commits and build successfully! Added AR features now in [my fork](https://github.com/DevPika/jumpy-balls-xr/) , have fun! :-D
